#!/usr/bin/env python3
import argparse
import sys
import os


def parse_args():
    parser = argparse.ArgumentParser(
        description="PoreSignalExtractor: A unified tool to extract raw ionic current mapped to genomic coordinates from Nanopore POD5 files.",
        epilog="Use '%(prog)s <command> -h' to see specific options for each extraction method."
    )
    
    subparsers = parser.add_subparsers(dest="command", help="Extraction method to use", required=True)

    # Common arguments parser
    common_parser = argparse.ArgumentParser(add_help=False)
    common_parser.add_argument("-p", "--pod5", required=True, nargs='+', help="Directory(ies) containing POD5 files.")
    common_parser.add_argument("-o", "--output", required=True, help="Path to the output TSV file.")
    common_parser.add_argument("-t", "--threads", type=int, default=1, help="Number of CPU cores to use for parallel processing (default: 1).")

    # Command 1: Moves (Dorado Basecaller alignment)
    parser_moves = subparsers.add_parser("moves", parents=[common_parser], help="Extract raw signal based on Dorado implicit alignment (BAM moves).")
    parser_moves.add_argument("-b", "--bam", required=True, help="Input BAM file generated by Dorado.")
    parser_moves.add_argument("-r", "--ref", required=True, help="Path to the reference genome FASTA file.")
    parser_moves.add_argument("--add-median", action="store_true", help="Include the median segment value in the output.")
    parser_moves.add_argument("--include-unmapped", action="store_true", help="Include reads not mapped to the reference.")

    # Command 2: Uncalled4 Reference Mode (Eventalign indices)
    parser_unc_ref = subparsers.add_parser("unc-ref", parents=[common_parser], help="Extract raw signal using Uncalled4 reference event alignment.")
    parser_unc_ref.add_argument("-m", "--map", required=True, help="TSV mapping file generated by 'uncalled4 convert --eventalign-out'.")

    # Command 3: Uncalled4 Self Mode (Read mapping)
    parser_unc_self = subparsers.add_parser("unc-self", parents=[common_parser], help="Extract raw signal using Uncalled4 self mapping with BAM and TSV.")
    parser_unc_self.add_argument("-b", "--bam", required=True, help="Input BAM file with Uncalled4 self-alignment.")
    parser_unc_self.add_argument("--self-tsv", required=True, help="TSV eventalign output from Uncalled4 self mode.")
    parser_unc_self.add_argument("--bed", required=False, help="Optional BED file to filter specific genomic positions.")

    # Command 4: F5C Self Mode
    parser_f5c = subparsers.add_parser("f5c-self", parents=[common_parser], help="Extract raw signal using F5C self mapping.")
    parser_f5c.add_argument("-b", "--bam", required=True, help="Input BAM file from F5C alignment.")
    parser_f5c.add_argument("-f", "--fasta", required=True, help="Reference FASTA file.")

    return parser.parse_args()


def main():
    args = parse_args()
    
    # Inizializza il logger base
    # logger = base.setup_logger()
    # logger.info(f"Starting PoreSignalExtractor with mode: {args.command}")
    
    # Controllo che i POD5 esistano
    for p_dir in args.pod5:
        if not os.path.exists(p_dir):
            sys.exit(f"Error: POD5 directory not found: {p_dir}")

    try:
        if args.command == "moves":
            pass # moves.run(args)
        elif args.command == "unc-ref":
            pass # uncalled_ref.run(args)
        elif args.command == "unc-self":
            pass # uncalled_self.run(args)
        elif args.command == "f5c-self":
            pass # f5c_self.run(args)
            
        # logger.info(f"Extraction completed successfully. Output written to {args.output}")
        
    except Exception as e:
        # logger.error(f"Extraction failed: {e}", exc_info=True)
        sys.exit(1)

if __name__ == "__main__":
    main()