"""
Executor for extracting raw signal based on Uncalled4 reference event alignment.
This module processes large TSV mapping files generated by 'uncalled4 convert --eventalign-out'
using Pandas chunking and optimized batch I/O operations for POD5 files.
"""
import os
import time
import pandas as pd
import pod5
import sqlite3
import logging

from core import config
from core import base
from core import signal_math

logger = logging.getLogger(__name__)

def run(args):
    """
    Main entry point for the 'unc-ref' extraction subcommand.
    """
    db_path = "uncalled_ref_map.db"
    
    # 1. Indexing
    base.index_pod5_files(args.pod5, db_path)
    
    conn = sqlite3.connect(db_path)
    c = conn.cursor()
    
    logger.info(f"Parsing mapping file: {args.map} in chunks of {config.EVENTALIGN_CHUNK_SIZE} rows")
    
    with open(args.output, 'w') as out_f:
        # Write standard header
        out_f.write("read_id\tcontig\tposition\tref_kmer\tsamples_pA\n")
        
        # Open a Pandas iterator to process the large TSV in chunks to prevent RAM exhaustion
        map_iter = pd.read_csv(
            args.map, 
            sep='\t', 
            chunksize=config.EVENTALIGN_CHUNK_SIZE, 
            usecols=['read_name', 'contig', 'position', 'reference_kmer', 'start_idx', 'end_idx']
        )
        
        for i, chunk in enumerate(map_iter):
            t0_chunk = time.time()
            
            unique_reads = chunk['read_name'].unique()
            
            # 2. Group reads by POD5 file using the SQLite index
            # This minimizes the overhead of opening and closing POD5 files
            file_batch_map = {}
            for r_id in unique_reads:
                str_r_id = str(r_id)
                c.execute("SELECT path FROM pod5_map WHERE read_name = ?", (str_r_id,))
                res = c.fetchone()
                if res:
                    p_path = res[0]
                    if p_path not in file_batch_map:
                        file_batch_map[p_path] = []
                    file_batch_map[p_path].append(str_r_id)

            # 3. Extract all required signals for the current chunk into RAM (Batch Reading)
            signal_cache = {}
            for p_path, read_ids in file_batch_map.items():
                try:
                    with pod5.Reader(p_path) as reader:
                        # reader.reads(list) is highly optimized in the pod5 library 
                        # for fetching multiple reads simultaneously
                        for record in reader.reads(read_ids):
                            signal_cache[str(record.read_id)] = signal_math.get_picoampere_signal(record)
                except Exception as e:
                    logger.warning(f"Error reading batch from {p_path}: {e}")

            # 4. Process the chunk data and extract the specific segments
            grouped = chunk.groupby("read_name")
            lines_written = 0
            
            for read_id, group in grouped:
                read_id_str = str(read_id)
                
                # Skip if the signal could not be fetched
                if read_id_str not in signal_cache:
                    continue
                
                full_signal = signal_cache[read_id_str]
                sig_len = len(full_signal)
                
                for row in group.itertuples():
                    start = int(row.start_idx)
                    end = int(row.end_idx)
                    
                    # Sanity check for boundary conditions
                    if start < 0 or end > sig_len or start >= end:
                        continue
                    
                    raw_slice = full_signal[start:end]
                    sig_str = ",".join([f"{x:.1f}" for x in raw_slice])
                    
                    # Write immediately to output file
                    out_f.write(f"{read_id}\t{row.contig}\t{row.position}\t{row.reference_kmer}\t{sig_str}\n")
                    lines_written += 1
            
            # Free up memory at the end of each chunk
            del signal_cache
            del file_batch_map
            
            dt = time.time() - t0_chunk
            logger.info(f"Finished chunk {i+1} ({len(chunk)} lines map -> {lines_written} lines out) in {dt:.2f}s")

    conn.close()
    
    # Cleanup SQLite DB
    if os.path.exists(db_path):
        os.remove(db_path)
        
    logger.info("Uncalled4 reference extraction completed successfully.")